### ISSUE TITLE
Change fillGridWithSubgrid to return a new variable rather than modify a reference to one of its parameters

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#46]
It just ain't right.

**Comment by davidabrahams** [comment]
I'm not sure I agree. Yes, it's not generally advised, but in this case it was an intentional choice I made. The only alternative is to copy the entire large array every time fillGridWithSubgrid is called. Given that for the entire tagpro map, we'll call fillGridWithSubgrid 100s of times (per game frame), i think we want to just keep one reference to the large grid

**Comment by shanek21** [comment]
Oh, my b. I guess I just assumed it was one of the functions I just finished writing.

**Comment by davidabrahams** [comment]
Hey guys! We're closing issues! Good work! Progress!
